#pragma once

#include "AsukaLib.h"

typedef ULONG   (WINAPI *FuncPtrIURelease)(IUnknown *IU);
typedef HRESULT (WINAPI *FuncPtrDirectSoundCreate8)(LPCGUID, LPDIRECTSOUND8 *, LPUNKNOWN);
typedef HRESULT (WINAPI *FuncPtrDSCreateSoundBuffer)(LPDIRECTSOUND8, LPCDSBUFFERDESC, LPDIRECTSOUNDBUFFER8 *, LPUNKNOWN);
typedef HRESULT (WINAPI *FuncPtrDSSBPlay)(LPDIRECTSOUNDBUFFER8, DWORD, DWORD, DWORD);
typedef HRESULT (WINAPI *FuncPtrDSSBSetVolume)(LPDIRECTSOUNDBUFFER8, LONG);
typedef HRESULT (WINAPI *FuncPtrDSSBUnlock)(LPDIRECTSOUNDBUFFER8, LPVOID, DWORD, LPVOID, DWORD);

ULONG WINAPI IURelease(IUnknown *IU);
HRESULT WINAPI DSCreateSoundBuffer(LPDIRECTSOUND8 lpds8, LPCDSBUFFERDESC pcDSBufferDesc, LPDIRECTSOUNDBUFFER8 *ppDSBuffer, LPUNKNOWN pUnkOuter);
HRESULT WINAPI DSSBPlay(LPDIRECTSOUNDBUFFER8 lpdssb8, DWORD dwReserved1, DWORD dwPriority, DWORD dwFlags);
HRESULT WINAPI DSSBSetVolume(LPDIRECTSOUNDBUFFER8 lpdssb8, LONG lVolume);
HRESULT WINAPI DSSBUnlock(LPDIRECTSOUNDBUFFER8 lpdssb8, LPVOID pvAudioPtr1, DWORD dwAudioBytes1, LPVOID pvAudioPtr2, DWORD dwAudioBytes2);
