#pragma once
#include <dinput.h>

#include "AsukaLib.h"

typedef HRESULT (WINAPI *FuncPtrDirectInput8Create)(HINSTANCE, DWORD, REFIID, LPVOID *, LPUNKNOWN);
typedef HRESULT (WINAPI *FuncPtrDICreateDevice)(LPDIRECTINPUT, REFGUID, LPDIRECTINPUTDEVICE *, LPUNKNOWN);
typedef HRESULT (WINAPI *FuncPtrDIDAcquire)(LPDIRECTINPUTDEVICE);
typedef HRESULT (WINAPI *FuncPtrDIDGetDeviceState)(LPDIRECTINPUTDEVICE, DWORD, LPDIMOUSESTATE);

HRESULT WINAPI DICreateDevice(LPDIRECTINPUT lpdi, REFGUID rguid,LPDIRECTINPUTDEVICE *lplpdid, LPUNKNOWN pu);
HRESULT WINAPI DIDAcquire(LPDIRECTINPUTDEVICE lpdid);
HRESULT WINAPI DIDGetDeviceState(LPDIRECTINPUTDEVICE lpdid, DWORD cbdata, LPDIMOUSESTATE lpvdata);
